### ISSUE TITLE
`UpdateRemotePlugins` fails

### ISSUE THREAD

**Issue by jbaiter** [snoe/nvim-parinfer.js#13]
With the lastes neovim checkout I get the following error when I'm running `UpdateRemotePlugins`:

```
2016/02/13 12:06:16 [info @ main:523] 10252 - Starting Neovim main loop.
2016/02/13 12:06:27 [error @ forward_stderr:333] 10252 - Channel 2 stderr: events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: list argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:229:13)
    at BufferList.copy (/home/jojo/.config/nvim/plugged/node-host/node_modules/bl/bl.js
2016/02/13 12:06:27 [error @ forward_stderr:333] 10252 - Channel 2 stderr: :118:21)
    at BufferList.slice (/home/jojo/.config/nvim/plugged/node-host/node_modules/bl/bl.js:93:15)
    at Object.encode (/home/jojo/.config/nvim/plugged/node-host/node_modules/msgpack5/index.js:188:18)
    at Encoder._transform (/home/jojo/.config/n
2016/02/13 12:06:27 [error @ forward_stderr:333] 10252 - Channel 2 stderr: vim/plugged/node-host/node_modules/msgpack5/lib/streams.js:37:25)
    at Encoder.Transform._read (/home/jojo/.config/nvim/plugged/node-host/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Encoder.Transform._write (/home/jojo/.config/n
2016/02/13 12:06:27 [error @ forward_stderr:333] 10252 - Channel 2 stderr: vim/plugged/node-host/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/jojo/.config/nvim/plugged/node-host/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/jojo/.config/nvim/plugge
2016/02/13 12:06:27 [error @ forward_stderr:333] 10252 - Channel 2 stderr: d/node-host/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Encoder.Writable.write (/home/jojo/.config/nvim/plugged/node-host/node_modules/readable-stream/lib/_stream_writable.js:211:11)

2016/02/13 12:06:27 [error @ call_set_error:743] 10252 - msgpack-rpc: Channel was closed by the client
```

I also ran it with `NEOVIM_JS_DEBUG`, but the log file is empty.

**Comment by jbaiter** [comment]
Nevermind, this was due to a bad Node.JS installation. I switched to v0.12.10 with `nvm` and everything works.
